### ISSUE TITLE
Use-Case Diagramm erstellen

### ISSUE THREAD

**Issue by Edranael** [crescendolll/lotto#4]
Use-Case Diagramm zu  Issue #3 erstellen

**Comment by crescendolll** [comment]
![Aktivitatsdiagramm](https://user-images.githubusercontent.com/72411231/129012828-dd574447-449b-4795-b9e5-c075dda37429.png)

Aktuelle Version als .png
Habe auch die .dia Version für ggf. Abänderungen

**Comment by crescendolll** [comment]
![Aktivitatsdiagramm](https://user-images.githubusercontent.com/72411231/129169813-60328bab-a94f-4aa4-923d-19bc3f645168.png)

Updated Version inkl. Kontolöschungs Aktivität
