### ISSUE TITLE
Async Vanilla JavaScript recherchieren bzw. Framework für API Interaktion raussuchen

### ISSUE THREAD

**Issue by Edranael** [crescendolll/lotto#6]

**Comment by crescendolll** [comment]
lt Recherchen passen react und go ganz gut zusammen (es gibt sogar einen go -> js5 transpiler) - da ich bislang im js Bereich eigtl nur mit React gearbeitet habe und es das create-react-app Modul gibt würde ich dieses für unser Projekt nutzen.

Contra-Vanillla-JS spricht außerdem, dass das Aufsetzen eines Projekts und das Aktualisieren von einzelnen DOM-Elementen hiermit sehr aufwändig und umständlich wäre.

Bsp/Ressourcen für die Kombi Go Backend, React Frontend:
- https://medium.com/@madhanganesh/golang-react-application-2aaf3bca92b1
- https://levelup.gitconnected.com/build-a-todo-app-in-golang-mongodb-and-react-e1357b4690a6

performantes framework für http requests mit Go:
https://gin-gonic.com/docs/
