### ISSUE TITLE
Frontendinteraktion mit API implementieren

### ISSUE THREAD

**Issue by crescendolll** [crescendolll/lotto#9]
(im es bei Frontendentwicklung ohne DB-Anbindung zu nutzen)

**Comment by crescendolll** [comment]
(evtl hilfreich: https://www.youtube.com/watch?v=FLnxgSZ0DG4)

**Comment by crescendolll** [comment]
Hier erste Version
https://github.com/crescendolll/lotto/blob/main/lotto-ui/src/mockdata.json

**Comment by Edranael** [comment]
Anmerkung: die API ist nicht in Stein gemeißelt, sollte beim Umsetzen der Webseite Bedarf an neuen Funktionen oder Änderungen an den bestehenden entstehen, kann das Issue für die Backendimplementierung wieder aufgemacht werden

**Comment by crescendolll** [comment]
see api.js
